https://www.kaggle.com/code/ishandutta/ag-news-classification-lstm/output

In [15]:
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.preprocessing.text import Tokenizer
# import numpy as np # linear algebra
# import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# TRAIN_FILE_PATH = './data/train.csv'
# TEST_FILE_PATH = './data//test.csv'

# #Load Data
# data = pd.read_csv(TRAIN_FILE_PATH)
# testdata = pd.read_csv(TEST_FILE_PATH)

# #Set Column Names 
# data.columns = ['ClassIndex', 'Title', 'Description']
# testdata.columns = ['ClassIndex', 'Title', 'Description']

# #Combine Title and Description
# X_train = data['Title'] + " " + data['Description'] # Combine title and description (better accuracy than using them as separate features)
# y_train = data['ClassIndex'].apply(lambda x: x-1).values # Class labels need to begin from 0

# x_test = testdata['Title'] + " " + testdata['Description'] # Combine title and description (better accuracy than using them as separate features)
# y_test = testdata['ClassIndex'].apply(lambda x: x-1).values # Class labels need to begin from 0
# vocab_size = 10000 
# tok = Tokenizer(num_words=vocab_size)
# maxlen = X_train.map(lambda x: len(x.split())).max()
# print(maxlen)

177


In [19]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
model = tf.keras.models.load_model('./models/model.hdf5')
# model.load_weights('./models/weights.h5')
# model.set_weights(weight)

In [20]:
from termcolor import colored
def modelDemo(news_text):
 
  token = Tokenizer()
  #News Labels
  labels = ['Business News', 'Sports News', 'World News', 'Science-Technology News']

  test_seq = pad_sequences(token.texts_to_sequences(news_text), maxlen=177)
  print(model.predict(test_seq))

  test_preds = [labels[np.argmax(i)] for i in model.predict(test_seq)]

  for news, label in zip(news_text, test_preds):
      # print('{} - {}'.format(news, label))
      print('{} - {}'.format(colored(news, 'yellow'), colored(label, 'blue')))

In [21]:
modelDemo(['Coronavirus: Bank pumps £100bn into UK economy to aid recovery'])

1/1 [==============================] - 5s 5s/step
[[0.35987437 0.13496095 0.32800648 0.17715818]]
1/1 [==============================] - 0s 59ms/step
Coronavirus: Bank pumps £100bn into UK economy to aid recovery - Business News


In [22]:
modelDemo(['David Luiz’s future with Arsenal to be decided this week'])

1/1 [==============================] - 0s 68ms/step
[[0.35987437 0.13496095 0.32800648 0.17715818]]
1/1 [==============================] - 0s 92ms/step
David Luiz’s future with Arsenal to be decided this week - Business News


In [23]:
modelDemo(['Indian Economic budget supports the underprivileged sections of society'])

1/1 [==============================] - 0s 103ms/step
[[0.35987437 0.13496095 0.32800648 0.17715818]]
1/1 [==============================] - 0s 137ms/step
Indian Economic budget supports the underprivileged sections of society - Business News


In [24]:
modelDemo([''])

1/1 [==============================] - 0s 85ms/step
[[0.35987437 0.13496095 0.32800648 0.17715818]]
1/1 [==============================] - 0s 143ms/step
 - Business News
